Added suppression property to discovery model for person/educationAnd…
TAMULib/scholars-discovery pull request #192
Opened 2022-12-07 20:47 UTC by jeremythuff

…Training

Co-authored-by: William Welling <wwelling@library.tamu.edu>

2022-12-14 16:03 UTC, rmathew1011 requested changes
Extra line needed src/main/resources/templates/sparql/person/educationAndTrainingIsDateSuppressed.sparql

2022-12-15 14:53 UTC, wwelling commented
@rmathew1011 we are not yet follow posix standard and requiring the newline for these files. If we do, we will have to update all the others for consistency.

2022-12-19 19:46 UTC, kaladay requested changes

2022-12-19 19:46 UTC, kaladay commented on src/main/resources/templates/sparql/person/educationAndTrainingIsDateSuppressed.sparql
> +}
Missing trailing new line.

2022-12-19 19:47 UTC, kaladay approved these changes

2022-12-19 19:47 UTC, kaladay commented on src/main/resources/templates/sparql/person/educationAndTrainingIsDateSuppressed.sparql
> +}
At glance this seems rather common so I am going to instead have this a suggestion rather than a change request.

2022-12-19 21:46 UTC, merged